"""
Dependency-free mock provider server for offline performance and CI testing
(Module 1.6.2).

Serves an OpenAI-compatible subset of the SDK's provider wire API over a
plain stdlib HTTP server (no Flask/uvicorn dependency), so KPI regression
tests can exercise the full client -> middleware -> adapter -> network ->
parse pipeline without live provider credentials or real network latency.

Endpoints (any base path ending in these suffixes is accepted, mirroring
how the client appends ``/chat/completions`` to the provider base URL):

* ``POST .../chat/completions`` — JSON completion, or SSE streaming when
  the request body sets ``stream: true``
* ``POST .../embeddings`` — OpenAI-compatible embedding payload

Usage:

.. code-block:: python

    from uai.testing import MockProviderServer

    with MockProviderServer(latency_ms=5.0) as server:
        print(server.base_url)          # http://127.0.0.1:PORT/v1
        print(server.port)
        # point a UniversalAI client at it via UAI_PROVIDER_*_BASE_URL

The server is thread-safe (each request handled on its own thread), tracks
``request_count``, and can inject transient failures via :meth:`fail_with`
so retry/backoff behaviour can be validated offline.
"""

from __future__ import annotations

import json
import math
import threading
import time
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from typing import Any, cast

__all__ = ["MockProviderServer"]


class _MockHTTPServer(ThreadingHTTPServer):
    """Threading HTTP server carrying a back-reference to its owner."""

    owner: MockProviderServer


_CHAT_COMPLETION_CONTENT = (
    "This is a mock completion generated by the uai-sdk testing server. "
    "It stands in for a real provider so performance and integration tests "
    "can run fully offline."
)


def _approx_tokens(text: str) -> int:
    """Rough token estimate (chars / 4) matching the SDK's benchmark helper."""
    return max(1, len(text) // 4)


class _MockHandler(BaseHTTPRequestHandler):
    """Serve one request against the owning :class:`MockProviderServer`."""

    server_version = "MockProviderServer/1.0"

    def log_message(self, format: str, *args: Any) -> None:  # silence access logs
        return

    @property
    def owner(self) -> MockProviderServer:
        return cast(_MockHTTPServer, self.server).owner

    def _read_body(self) -> dict[str, Any]:
        length = int(self.headers.get("Content-Length") or 0)
        raw = self.rfile.read(length) if length else b"{}"
        try:
            return cast(dict[str, Any], json.loads(raw.decode("utf-8") or "{}"))
        except json.JSONDecodeError:
            return {}

    def _send_json(self, status: int, payload: dict[str, Any]) -> None:
        body = json.dumps(payload).encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    # ------------------------------------------------------------------
    # Routing
    # ------------------------------------------------------------------

    def do_POST(self) -> None:
        owner = self.owner
        owner.request_count += 1
        body = self._read_body()

        if owner._failures:  # fail before serving, then recover
            status, remaining = owner._failures[0]
            if remaining <= 1:
                owner._failures.pop(0)
            else:
                owner._failures[0] = (status, remaining - 1)
            self._send_json(
                status,
                {"error": {"message": "injected mock failure", "type": "mock_error"}},
            )
            return

        if owner.latency_ms:
            time.sleep(owner.latency_ms / 1000.0)

        path = self.path.split("?")[0]
        if path.endswith("/chat/completions"):
            if body.get("stream"):
                self._stream_chat(body)
            else:
                self._send_json(200, self._chat_completion(body))
        elif path.endswith("/embeddings"):
            self._send_json(200, self._embeddings(body))
        else:
            self._send_json(404, {"error": {"message": f"unknown path {path}"}})

    # ------------------------------------------------------------------
    # Chat
    # ------------------------------------------------------------------

    def _chat_completion(self, body: dict[str, Any]) -> dict[str, Any]:
        owner = self.owner
        model = body.get("model", "mock-model")
        content = _CHAT_COMPLETION_CONTENT
        return {
            "id": f"mock-cmpl-{owner.request_count}",
            "object": "chat.completion",
            "created": 1_700_000_000,
            "model": model,
            "choices": [
                {
                    "index": 0,
                    "message": {"role": "assistant", "content": content},
                    "finish_reason": "stop",
                }
            ],
            "usage": {
                "prompt_tokens": 16,
                "completion_tokens": _approx_tokens(content),
                "cache_read_input_tokens": 0,
                "cache_creation_input_tokens": 0,
            },
        }

    def _stream_chat(self, body: dict[str, Any]) -> None:
        """Emit a Server-Sent-Events stream of chunks then ``[DONE]``."""
        owner = self.owner
        model = body.get("model", "mock-model")
        words = _CHAT_COMPLETION_CONTENT.split(" ")
        # Emit one chunk per word so TTFT / streaming overhead is measurable.
        self.send_response(200)
        self.send_header("Content-Type", "text/event-stream")
        self.send_header("Cache-Control", "no-cache")
        self.end_headers()
        try:
            for word in words:
                if owner.chunk_delay_ms:
                    time.sleep(owner.chunk_delay_ms / 1000.0)
                payload = {
                    "id": f"mock-cmpl-{owner.request_count}",
                    "object": "chat.completion.chunk",
                    "created": 1_700_000_000,
                    "model": model,
                    "choices": [
                        {
                            "index": 0,
                            "delta": {"content": word + " "},
                            "finish_reason": None,
                        }
                    ],
                }
                self.wfile.write(f"data: {json.dumps(payload)}\n\n".encode())
                self.wfile.flush()
            # Terminal chunk with finish_reason + usage, then [DONE].
            final = {
                "id": f"mock-cmpl-{owner.request_count}",
                "object": "chat.completion.chunk",
                "model": model,
                "choices": [{"index": 0, "delta": {}, "finish_reason": "stop"}],
                "usage": {
                    "prompt_tokens": 16,
                    "completion_tokens": len(words),
                    "cache_read_input_tokens": 0,
                    "cache_creation_input_tokens": 0,
                },
            }
            self.wfile.write(f"data: {json.dumps(final)}\n\n".encode())
            self.wfile.write(b"data: [DONE]\n\n")
            self.wfile.flush()
        except (BrokenPipeError, ConnectionResetError):
            return  # client closed early — not an error worth reporting

    # ------------------------------------------------------------------
    # Embeddings
    # ------------------------------------------------------------------

    def _embeddings(self, body: dict[str, Any]) -> dict[str, Any]:
        owner = self.owner
        model = body.get("model", "mock-embedding")
        inputs = body.get("input", [])
        if isinstance(inputs, str):
            inputs = [inputs]
        data = []
        total_tokens = 0
        for i, text in enumerate(inputs):
            # Deterministic pseudo-random vector so tests can assert shape.
            vector = [round(math.sin((i + 1) * (j + 1)) * 10, 4) for j in range(owner.embed_dim)]
            data.append({"object": "embedding", "embedding": vector, "index": i})
            total_tokens += _approx_tokens(text)
        return {
            "object": "list",
            "data": data,
            "model": model,
            "usage": {"prompt_tokens": total_tokens, "total_tokens": total_tokens},
        }


class MockProviderServer:
    """
    An in-process mock provider serving OpenAI-compatible chat/embeddings.

    Args:
        host: Bind host (default ``127.0.0.1``).
        port: Bind port (``0`` = ephemeral).
        latency_ms: Artificial per-request latency added before responding.
        chunk_delay_ms: Delay between SSE chunks in streaming mode.
        embed_dim: Dimensionality of the mock embedding vectors.
    """

    def __init__(
        self,
        host: str = "127.0.0.1",
        port: int = 0,
        latency_ms: float = 0.0,
        chunk_delay_ms: float = 0.0,
        embed_dim: int = 8,
    ) -> None:
        self.host = host
        self.port = port
        self.latency_ms = latency_ms
        self.chunk_delay_ms = chunk_delay_ms
        self.embed_dim = embed_dim
        self.request_count = 0
        self._failures: list[tuple[int, int]] = []
        self._httpd: _MockHTTPServer | None = None
        self._thread: threading.Thread | None = None

    # ------------------------------------------------------------------
    # Lifecycle
    # ------------------------------------------------------------------

    @property
    def base_url(self) -> str:
        """The client-facing base URL (``http://host:port/v1``)."""
        if self._httpd is None:
            raise RuntimeError("MockProviderServer is not running")
        return f"http://{self.host}:{self.server_port}/v1"

    @property
    def server_port(self) -> int:
        if self._httpd is None:
            raise RuntimeError("MockProviderServer is not running")
        return int(self._httpd.server_address[1])

    def fail_with(self, status: int, count: int = 1) -> None:
        """
        Inject *count* consecutive responses with HTTP *status*.

        Used to exercise retry / circuit-breaker behaviour offline; the
        server recovers automatically once the failures are exhausted.
        """
        if count < 1:
            raise ValueError("count must be >= 1")
        self._failures.append((status, count))

    def start(self) -> MockProviderServer:
        """Start serving in a daemon thread. Idempotent."""
        if self._httpd is not None:
            return self

        server = _MockHTTPServer((self.host, self.port), _MockHandler)
        server.owner = self
        self._httpd = server
        self.port = self.server_port
        self._thread = threading.Thread(target=server.serve_forever, daemon=True)
        self._thread.start()
        return self

    def stop(self) -> None:
        """Shut the server down (idempotent, safe to call from anywhere)."""
        if self._httpd is not None:
            self._httpd.shutdown()
            self._httpd.server_close()
            self._httpd = None
        if self._thread is not None:
            self._thread.join(timeout=2)
            self._thread = None

    def __enter__(self) -> MockProviderServer:
        return self.start()

    def __exit__(self, *exc: Any) -> None:
        self.stop()
